name: Deploy to FTP

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [microcms-update]

jobs:
  web-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: |
        echo "MICROCMS_SERVICE_DOMAIN=${{ secrets.MICROCMS_SERVICE_DOMAIN }}" >> .env
        echo "MICROCMS_API_KEY=${{ secrets.MICROCMS_API_KEY }}" >> .env
        npm run build

    - name: Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /www/tohoku.sfj.or.jp/html/
        local-dir: ./dist/
        
